/**
 * Procedural ambient soundscapes built entirely with the native Web Audio API.
 * Zero external assets — every texture is synthesised from noise buffers,
 * filters and slow LFOs so the app works fully offline.
 *
 * Every generator returns a "voice": { nodes, output, start(), stop() }
 * The caller connects `output` to a master gain and calls start()/stop().
 */

const NOISE_SECONDS = 3

/** Flat-spectrum white noise buffer (base material for everything else). */
export const createWhiteNoiseBuffer = (ctx) => {
  const length = ctx.sampleRate * NOISE_SECONDS
  const buffer = ctx.createBuffer(1, length, ctx.sampleRate)
  const data = buffer.getChannelData(0)
  for (let i = 0; i < length; i++) data[i] = Math.random() * 2 - 1
  return buffer
}

/** Brown (red) noise — deep, ocean-like rumble. */
export const createBrownNoiseBuffer = (ctx) => {
  const length = ctx.sampleRate * NOISE_SECONDS
  const buffer = ctx.createBuffer(1, length, ctx.sampleRate)
  const data = buffer.getChannelData(0)
  let lastOut = 0.0
  for (let i = 0; i < length; i++) {
    const white = Math.random() * 2 - 1
    data[i] = (lastOut + 0.02 * white) / 1.02
    lastOut = data[i]
    data[i] *= 3.5 // gain compensation
  }
  return buffer
}

/** Pink noise (Paul Kellet's economy filter) — soft, rain-like hiss. */
export const createPinkNoiseBuffer = (ctx) => {
  const length = ctx.sampleRate * NOISE_SECONDS
  const buffer = ctx.createBuffer(1, length, ctx.sampleRate)
  const data = buffer.getChannelData(0)
  let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0
  for (let i = 0; i < length; i++) {
    const white = Math.random() * 2 - 1
    b0 = 0.99886 * b0 + white * 0.0555179
    b1 = 0.99332 * b1 + white * 0.0750759
    b2 = 0.969 * b2 + white * 0.153852
    b3 = 0.8665 * b3 + white * 0.3104856
    b4 = 0.55 * b4 + white * 0.5329522
    b5 = -0.7616 * b5 - white * 0.016898
    data[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * 0.11
    b6 = white * 0.115926
  }
  return buffer
}

/** Convenience: a looping buffer source ready to start. */
const loopingSource = (ctx, buffer) => {
  const src = ctx.createBufferSource()
  src.buffer = buffer
  src.loop = true
  return src
}

/**
 * A slow sine LFO modulating a target AudioParam — this is what makes the
 * textures feel like they are breathing rather than sitting flat.
 */
const slowLfo = (ctx, { rate, depth, offset = 0, target }) => {
  const osc = ctx.createOscillator()
  osc.type = 'sine'
  osc.frequency.value = rate
  const gain = ctx.createGain()
  gain.gain.value = depth
  osc.connect(gain)
  if (target) {
    target.value = offset
    gain.connect(target)
  }
  return { osc, gain }
}

/* ------------------------------------------------------------------ */
/* Instruments — pitched voices, still synthesised from scratch        */
/* ------------------------------------------------------------------ */

const SEMITONES = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 }

/** 'F#3' | 'Bb4' | 'A3' -> frequency in Hz (A4 = 440). */
const noteFreq = (name) => {
  const [, letter, accidental, octave] = /^([A-G])([#b]?)(-?\d)$/.exec(name)
  const semitone = SEMITONES[letter] + (accidental === '#' ? 1 : accidental === 'b' ? -1 : 0)
  const midi = (Number(octave) + 1) * 12 + semitone
  return 440 * 2 ** ((midi - 69) / 12)
}

/**
 * Impulse response for a small, soft room: decaying noise. The tail is most
 * of what makes a pitched voice read as "played in a room" rather than
 * "generated by an oscillator".
 */
const createImpulseResponse = (ctx, { seconds = 2.8, decay = 3.2 } = {}) => {
  const length = Math.floor(ctx.sampleRate * seconds)
  const buffer = ctx.createBuffer(2, length, ctx.sampleRate)
  for (let channel = 0; channel < 2; channel++) {
    const data = buffer.getChannelData(channel)
    for (let i = 0; i < length; i++) {
      data[i] = (Math.random() * 2 - 1) * (1 - i / length) ** decay
    }
  }
  return buffer
}

/** A reverb send: play notes into `input`, patch `output` into the mix. */
const createReverb = (ctx, { seconds, decay, wet = 0.3 } = {}) => {
  const input = ctx.createGain()
  const convolver = ctx.createConvolver()
  convolver.buffer = createImpulseResponse(ctx, { seconds, decay })
  const damp = ctx.createBiquadFilter()
  damp.type = 'lowpass'
  damp.frequency.value = 2600
  const output = ctx.createGain()
  output.gain.value = wet
  input.connect(convolver).connect(damp).connect(output)
  return { input, output }
}

/**
 * A felt-piano note: sine partials with their own decay rates under a lowpass
 * that closes as the note rings out — a struck string loses its brightness
 * well before it loses its volume.
 */
const pianoNote = (ctx, { frequency, at, velocity = 0.4, decay = 5, destination, send }) => {
  const now = Math.max(at, ctx.currentTime)

  const tone = ctx.createBiquadFilter()
  tone.type = 'lowpass'
  tone.Q.value = 0.35
  tone.frequency.setValueAtTime(Math.min(frequency * 8, 5400), now)
  tone.frequency.exponentialRampToValueAtTime(Math.max(frequency * 2, 260), now + decay * 0.75)

  const env = ctx.createGain()
  env.gain.setValueAtTime(0.0001, now)
  env.gain.exponentialRampToValueAtTime(velocity, now + 0.014)
  env.gain.exponentialRampToValueAtTime(0.0001, now + decay)

  // [ratio, level, share of the total decay]
  const partials = [
    [1, 1, 1],
    [2, 0.3, 0.62],
    [3.01, 0.12, 0.42],
    [4.02, 0.05, 0.28],
  ]

  const oscs = partials.map(([ratio, level, life]) => {
    const osc = ctx.createOscillator()
    osc.type = 'sine'
    osc.frequency.value = frequency * ratio
    const gain = ctx.createGain()
    gain.gain.setValueAtTime(level, now)
    gain.gain.exponentialRampToValueAtTime(0.0001, now + decay * life)
    osc.connect(gain).connect(tone)
    osc.start(now)
    osc.stop(now + decay + 0.2)
    return osc
  })

  tone.connect(env)
  env.connect(destination)
  if (send) env.connect(send)

  oscs[0].onended = () => {
    try {
      env.disconnect()
      tone.disconnect()
    } catch {
      /* already torn down */
    }
  }
}

/**
 * A bowed chord: detuned saw pairs per note, opened and closed slowly enough
 * that consecutive chords overlap into one another instead of stepping.
 */
const stringChord = (
  ctx,
  { frequencies, at, duration = 7, level = 0.14, attack = 2.2, release = 3, destination, send },
) => {
  const now = Math.max(at, ctx.currentTime)

  const body = ctx.createBiquadFilter()
  body.type = 'lowpass'
  body.Q.value = 0.5
  body.frequency.setValueAtTime(900, now)
  body.frequency.linearRampToValueAtTime(1500, now + attack)
  body.frequency.linearRampToValueAtTime(820, now + duration + release)

  const env = ctx.createGain()
  env.gain.setValueAtTime(0.0001, now)
  env.gain.linearRampToValueAtTime(level, now + attack)
  env.gain.setValueAtTime(level, now + duration)
  env.gain.exponentialRampToValueAtTime(0.0001, now + duration + release)

  const oscs = []
  frequencies.forEach((frequency, index) => {
    // Quieter towards the top of the voicing, the way a section balances itself.
    const weight = 1 / (1 + index * 0.35)
    ;[-4, 4].forEach((detune) => {
      const osc = ctx.createOscillator()
      osc.type = 'sawtooth'
      osc.frequency.value = frequency
      osc.detune.value = detune
      const gain = ctx.createGain()
      gain.gain.value = 0.16 * weight
      osc.connect(gain).connect(body)
      osc.start(now)
      osc.stop(now + duration + release + 0.2)
      oscs.push(osc)
    })
  })

  body.connect(env)
  env.connect(destination)
  if (send) env.connect(send)

  oscs[0].onended = () => {
    try {
      env.disconnect()
      body.disconnect()
    } catch {
      /* already torn down */
    }
  }
}

/**
 * Note scheduler. `tick(at)` schedules whatever should sound at `at` and
 * returns the seconds to wait before the next call, so a generator can play
 * in strict time (a progression) or loosely (rain piano).
 */
const noteScheduler = (ctx, { delay = 0.1, tick }) => {
  let timer = null
  let stopped = false

  const run = () => {
    if (stopped) return
    const gap = tick(ctx.currentTime + 0.08)
    timer = window.setTimeout(run, gap * 1000)
  }

  return {
    start: () => {
      timer = window.setTimeout(run, delay * 1000)
    },
    stop: () => {
      stopped = true
      if (timer !== null) window.clearTimeout(timer)
      timer = null
    },
  }
}

/* ------------------------------------------------------------------ */
/* Soundscape recipes                                                  */
/* ------------------------------------------------------------------ */

/**
 * Gentle Rain — soft rainfall with an unhurried piano over it. The bed is
 * darker and quieter than plain rain noise so the notes have room; the piano
 * plays a pentatonic scale, where no two notes can clash, at intervals long
 * enough that it never becomes a melody to follow.
 */
const RAIN_PIANO_SCALE = ['F3', 'A3', 'C4', 'D4', 'F4', 'G4', 'A4', 'C5', 'D5', 'F5']

const gentleRain = (ctx) => {
  const src = loopingSource(ctx, createPinkNoiseBuffer(ctx))

  const body = ctx.createBiquadFilter()
  body.type = 'bandpass'
  body.frequency.value = 640
  body.Q.value = 0.5

  // Takes the hiss off the top of the bed — rain heard through glass.
  const muffle = ctx.createBiquadFilter()
  muffle.type = 'lowpass'
  muffle.frequency.value = 2400
  muffle.Q.value = 0.3

  const airSrc = loopingSource(ctx, createWhiteNoiseBuffer(ctx))
  const air = ctx.createBiquadFilter()
  air.type = 'highpass'
  air.frequency.value = 5200
  const airGain = ctx.createGain()
  airGain.gain.value = 0.02

  const rainGain = ctx.createGain()
  rainGain.gain.value = 0.62

  const out = ctx.createGain()
  out.gain.value = 0.9

  src.connect(body).connect(muffle).connect(rainGain).connect(out)
  airSrc.connect(air).connect(airGain).connect(rainGain)

  const reverb = createReverb(ctx, { seconds: 3.4, decay: 2.6, wet: 0.5 })
  reverb.output.connect(out)

  const piano = ctx.createGain()
  piano.gain.value = 0.9
  piano.connect(out)

  // Rain intensity gently swells and recedes.
  const lfo = slowLfo(ctx, { rate: 0.05, depth: 240, offset: 640, target: body.frequency })

  let lastIndex = -1
  const notes = noteScheduler(ctx, {
    delay: 1.6,
    tick: (at) => {
      // Never repeat the previous note; small steps are more common than leaps.
      let index = lastIndex
      while (index === lastIndex) {
        const drift = Math.floor(Math.random() * 5) - 2
        index =
          lastIndex < 0
            ? Math.floor(Math.random() * RAIN_PIANO_SCALE.length)
            : Math.min(RAIN_PIANO_SCALE.length - 1, Math.max(0, lastIndex + drift))
      }
      lastIndex = index

      const frequency = noteFreq(RAIN_PIANO_SCALE[index])
      pianoNote(ctx, {
        frequency,
        at,
        velocity: 0.16 + Math.random() * 0.1,
        decay: 6,
        destination: piano,
        send: reverb.input,
      })

      // Sometimes a quieter note answers it a beat later.
      if (Math.random() < 0.4) {
        const partner = Math.min(RAIN_PIANO_SCALE.length - 1, index + 2)
        pianoNote(ctx, {
          frequency: noteFreq(RAIN_PIANO_SCALE[partner]),
          at: at + 0.55 + Math.random() * 0.35,
          velocity: 0.09 + Math.random() * 0.05,
          decay: 5,
          destination: piano,
          send: reverb.input,
        })
      }

      return 4.5 + Math.random() * 4
    },
  })

  return {
    output: out,
    start: () => {
      src.start()
      airSrc.start()
      lfo.osc.start()
      notes.start()
    },
    stop: () => {
      src.stop()
      airSrc.stop()
      lfo.osc.stop()
      notes.stop()
    },
  }
}

/** Ocean Brown Noise — brown noise swelling like slow surf. */
const oceanBrownNoise = (ctx) => {
  const src = loopingSource(ctx, createBrownNoiseBuffer(ctx))

  const tone = ctx.createBiquadFilter()
  tone.type = 'lowpass'
  tone.frequency.value = 620
  tone.Q.value = 0.4

  const swell = ctx.createGain()
  swell.gain.value = 0.5

  const out = ctx.createGain()
  out.gain.value = 1

  src.connect(tone).connect(swell).connect(out)

  // ~11s wave period.
  const waves = slowLfo(ctx, { rate: 0.09, depth: 0.32, offset: 0.55, target: swell.gain })
  const brightness = slowLfo(ctx, { rate: 0.045, depth: 180, offset: 620, target: tone.frequency })

  return {
    output: out,
    start: () => { src.start(); waves.osc.start(); brightness.osc.start() },
    stop: () => { src.stop(); waves.osc.stop(); brightness.osc.stop() },
  }
}

/** Forest Wind — filtered white noise drifting through imaginary leaves. */
const forestWind = (ctx) => {
  const src = loopingSource(ctx, createWhiteNoiseBuffer(ctx))

  const gust = ctx.createBiquadFilter()
  gust.type = 'bandpass'
  gust.frequency.value = 520
  gust.Q.value = 1.6

  const leaves = loopingSource(ctx, createPinkNoiseBuffer(ctx))
  const leafFilter = ctx.createBiquadFilter()
  leafFilter.type = 'highpass'
  leafFilter.frequency.value = 2600
  const leafGain = ctx.createGain()
  leafGain.gain.value = 0.05

  const breath = ctx.createGain()
  breath.gain.value = 0.6

  const out = ctx.createGain()
  out.gain.value = 1

  src.connect(gust).connect(breath).connect(out)
  leaves.connect(leafFilter).connect(leafGain).connect(out)

  const sweep = slowLfo(ctx, { rate: 0.07, depth: 340, offset: 560, target: gust.frequency })
  const gusting = slowLfo(ctx, { rate: 0.033, depth: 0.3, offset: 0.55, target: breath.gain })
  const rustle = slowLfo(ctx, { rate: 0.12, depth: 0.035, offset: 0.05, target: leafGain.gain })

  return {
    output: out,
    start: () => {
      src.start(); leaves.start()
      sweep.osc.start(); gusting.osc.start(); rustle.osc.start()
    },
    stop: () => {
      src.stop(); leaves.stop()
      sweep.osc.stop(); gusting.osc.stop(); rustle.osc.stop()
    },
  }
}

/**
 * Soft Hum — a warm drone with a gentle 6 Hz binaural offset between ears,
 * layered over a whisper of noise so it never feels sterile.
 */
const softHum = (ctx) => {
  const baseFreq = 136.1 // "Om" / C#, a classic meditation tone
  const beat = 6 // theta-range binaural offset

  const merger = ctx.createChannelMerger(2)

  const left = ctx.createOscillator()
  left.type = 'sine'
  left.frequency.value = baseFreq

  const right = ctx.createOscillator()
  right.type = 'sine'
  right.frequency.value = baseFreq + beat

  const leftGain = ctx.createGain()
  const rightGain = ctx.createGain()
  leftGain.gain.value = 0.5
  rightGain.gain.value = 0.5

  left.connect(leftGain).connect(merger, 0, 0)
  right.connect(rightGain).connect(merger, 0, 1)

  // A fifth above, quietly, for warmth.
  const fifth = ctx.createOscillator()
  fifth.type = 'sine'
  fifth.frequency.value = baseFreq * 1.5
  const fifthGain = ctx.createGain()
  fifthGain.gain.value = 0.08

  // Whisper bed so the drone sits in a space.
  const bed = loopingSource(ctx, createBrownNoiseBuffer(ctx))
  const bedFilter = ctx.createBiquadFilter()
  bedFilter.type = 'lowpass'
  bedFilter.frequency.value = 320
  const bedGain = ctx.createGain()
  bedGain.gain.value = 0.12

  const warmth = ctx.createBiquadFilter()
  warmth.type = 'lowpass'
  warmth.frequency.value = 900

  const out = ctx.createGain()
  out.gain.value = 0.85

  merger.connect(warmth).connect(out)
  fifth.connect(fifthGain).connect(out)
  bed.connect(bedFilter).connect(bedGain).connect(out)

  const drift = slowLfo(ctx, { rate: 0.04, depth: 0.16, offset: 0.7, target: out.gain })

  return {
    output: out,
    start: () => { left.start(); right.start(); fifth.start(); bed.start(); drift.osc.start() },
    stop: () => { left.stop(); right.stop(); fifth.stop(); bed.stop(); drift.osc.stop() },
  }
}

/**
 * Classic Strings — a slow canon in D for string section, piano and a plucked
 * upper voice, over the eight-chord ground bass that most of the calm
 * classical repertoire is built on. Each bar re-voices itself slightly, so it
 * repeats without landing in exactly the same place twice.
 */
const CANON_PROGRESSION = [
  { pad: ['D3', 'A3', 'D4', 'F#4'], arp: ['D4', 'F#4', 'A4', 'D5', 'A4'] },
  { pad: ['A2', 'E3', 'A3', 'C#4'], arp: ['A3', 'C#4', 'E4', 'A4', 'E4'] },
  { pad: ['B2', 'F#3', 'B3', 'D4'], arp: ['B3', 'D4', 'F#4', 'B4', 'F#4'] },
  { pad: ['F#2', 'C#3', 'F#3', 'A3'], arp: ['F#3', 'A3', 'C#4', 'F#4', 'C#4'] },
  { pad: ['G2', 'D3', 'G3', 'B3'], arp: ['G3', 'B3', 'D4', 'G4', 'D4'] },
  { pad: ['D3', 'A3', 'D4', 'F#4'], arp: ['D4', 'F#4', 'A4', 'D5', 'F#4'] },
  { pad: ['G2', 'D3', 'G3', 'B3'], arp: ['G3', 'D4', 'G4', 'B4', 'G4'] },
  { pad: ['A2', 'E3', 'A3', 'C#4'], arp: ['A3', 'E4', 'A4', 'C#5', 'A4'] },
]

const CANON_BAR = 7.6

const classicStrings = (ctx) => {
  const out = ctx.createGain()
  out.gain.value = 0.9

  const reverb = createReverb(ctx, { seconds: 4, decay: 2.4, wet: 0.55 })
  reverb.output.connect(out)

  const strings = ctx.createGain()
  strings.gain.value = 0.85
  strings.connect(out)

  const keys = ctx.createGain()
  keys.gain.value = 0.7
  keys.connect(out)

  // Air around the section — a concert hall is never silent.
  const room = loopingSource(ctx, createPinkNoiseBuffer(ctx))
  const roomFilter = ctx.createBiquadFilter()
  roomFilter.type = 'lowpass'
  roomFilter.frequency.value = 900
  const roomGain = ctx.createGain()
  roomGain.gain.value = 0.035
  room.connect(roomFilter).connect(roomGain).connect(out)

  let bar = 0
  const notes = noteScheduler(ctx, {
    delay: 0.1,
    tick: (at) => {
      const { pad, arp } = CANON_PROGRESSION[bar % CANON_PROGRESSION.length]

      stringChord(ctx, {
        frequencies: pad.map(noteFreq),
        at,
        duration: CANON_BAR * 0.72,
        level: 0.13,
        attack: 2.4,
        release: 3.2,
        destination: strings,
        send: reverb.input,
      })

      // The upper line enters on the second pass and then stays.
      if (bar > 0) {
        arp.forEach((name, index) => {
          pianoNote(ctx, {
            frequency: noteFreq(name),
            at: at + 0.35 + index * 0.95,
            velocity: (index === 0 ? 0.17 : 0.12) - Math.random() * 0.03,
            decay: 5.5,
            destination: keys,
            send: reverb.input,
          })
        })
      }

      bar++
      return CANON_BAR
    },
  })

  // The section breathes across the whole progression, not bar by bar.
  const swell = slowLfo(ctx, { rate: 0.016, depth: 0.14, offset: 0.82, target: out.gain })

  return {
    output: out,
    start: () => {
      room.start()
      swell.osc.start()
      notes.start()
    },
    stop: () => {
      room.stop()
      swell.osc.stop()
      notes.stop()
    },
  }
}

/* ------------------------------------------------------------------ */

export const SOUNDSCAPES = [
  {
    id: 'classic',
    label: 'Classic Strings',
    description: 'A slow canon for strings and piano',
    emoji: '🎻',
    gain: 0.3,
    build: classicStrings,
  },
  {
    id: 'rain',
    label: 'Gentle Rain',
    description: 'Soft rainfall with an unhurried piano',
    emoji: '🌧️',
    gain: 0.36,
    build: gentleRain,
  },
  {
    id: 'ocean',
    label: 'Ocean Brown Noise',
    description: 'Deep, slow surf rolling in and out',
    emoji: '🌊',
    gain: 0.4,
    build: oceanBrownNoise,
  },
  {
    id: 'forest',
    label: 'Forest Wind',
    description: 'Wind drifting through distant leaves',
    emoji: '🌲',
    gain: 0.32,
    build: forestWind,
  },
  {
    id: 'hum',
    label: 'Soft Hum',
    description: 'A warm 136 Hz drone with a 6 Hz binaural pulse',
    emoji: '🔆',
    gain: 0.26,
    build: softHum,
  },
]

export const getSoundscape = (id) =>
  SOUNDSCAPES.find((s) => s.id === id) ?? SOUNDSCAPES[0]

/**
 * A short, soft bell used to mark breathing phase changes.
 * Self-contained: creates, plays and disposes its own nodes.
 */
export const playChime = (ctx, { frequency = 528, volume = 0.09 } = {}) => {
  if (!ctx || ctx.state === 'closed') return
  const now = ctx.currentTime
  const osc = ctx.createOscillator()
  osc.type = 'sine'
  osc.frequency.value = frequency

  const partial = ctx.createOscillator()
  partial.type = 'sine'
  partial.frequency.value = frequency * 2.01

  const partialGain = ctx.createGain()
  partialGain.gain.value = 0.25

  const env = ctx.createGain()
  env.gain.setValueAtTime(0.0001, now)
  env.gain.exponentialRampToValueAtTime(volume, now + 0.02)
  env.gain.exponentialRampToValueAtTime(0.0001, now + 1.6)

  osc.connect(env)
  partial.connect(partialGain).connect(env)
  env.connect(ctx.destination)

  osc.start(now)
  partial.start(now)
  osc.stop(now + 1.7)
  partial.stop(now + 1.7)
  osc.onended = () => {
    try {
      env.disconnect()
      partialGain.disconnect()
    } catch {
      /* already torn down */
    }
  }
}
